import pandas as pd
from http.client import responses


fetchpd = pd.read_csv("fetch_latimes.csv")
visit_pd = pd.read_csv("visit_latimes.csv")
url_pd = pd.read_csv("urls_latimes.csv")

f = open("CrawlReport_latimes.txt", "a")
f.write("Name: Gaurav Makasare\n")
f.write("USCID: 7559721394\n")
f.write("Site Crawled: latimes.com\n")
f.write("Number of threads: 7")


f.write("\n\n")
f.write("Fetch Statistics:\n")
f.write("=================\n")
f.write("# fetches attempted: ")
f.write(str(fetchpd.shape[0]))
f.write("\n")
f.write("# fetches succeeded: ")
f.write(str(visit_pd.shape[0]))
f.write("\n")
f.write("# fetches failed or aborted: ")
f.write(str(fetchpd.shape[0] - visit_pd.shape[0]))
f.write("\n\n")


# f.write(url_pd.shape[0])
f.write("Outgoing Links:")
f.write("\n")
f.write("===============")
f.write("\n")
f.write("Total urls extracted: ")
f.write(str(url_pd.shape[0]))
f.write("\n")
f.write("# unique URLs extracted: ")
f.write(str(len(set(url_pd['URL']))))
f.write("\n")
f.write("# unique URLs within News Site: ")
f.write(str(url_pd['OK or NOT OK'].value_counts()['OK']))
f.write("\n")
f.write("# unique URLs outside News Site: ")
f.write(str(url_pd['OK or NOT OK'].value_counts()['N_OK']))
f.write("\n\n")


# f.write("Unique Status Code: ", set(fetchpd['Status Code'].unique()))
s = set(fetchpd['Status Code'].unique())
f.write("Status Codes:")
f.write("\n")
f.write("=============")
f.write("\n")
for i in s:
    f.write(str(i))
    f.write(" ")
    f.write(responses[i])
    f.write(": ")
    f.write(str(fetchpd['Status Code'].value_counts()[i]))
    f.write("\n")
    
f.write("\n")
# df[(x <= df['columnX']) & (df['columnX'] <= y)]

f.write("File Sizes:" )
f.write("\n")
f.write("===========")
f.write("\n")
f.write("< 1KB: ")
f.write(str((visit_pd['Size in Bytes'] <= 1024).sum()))
f.write("\n")
f.write("1KB ~ <10KB: ")
f.write(str(((visit_pd['Size in Bytes'] > 1024) & (visit_pd['Size in Bytes'] <= 10240)).sum()))
f.write("\n")
f.write("10KB ~ <100KB: " )
f.write(str(((visit_pd['Size in Bytes'] > 10240) & (visit_pd['Size in Bytes'] <= 102400)).sum()))
f.write("\n")
f.write("100KB ~ <1MB: ")
f.write(str(((visit_pd['Size in Bytes'] > 102400) & (visit_pd['Size in Bytes'] <= 1048576)).sum()))
f.write("\n")
f.write(">= 1MB: ")
f.write(str((visit_pd['Size in Bytes'] > 1048576).sum()))
f.write("\n\n")

f.write("File types:")
f.write("\n")
f.write("===========")
f.write("\n")
t = set(visit_pd['Type'])
for i in t:
    f.write(str(i))
    f.write(" :")
    f.write(str(visit_pd['Type'].value_counts()[i]))
    f.write("\n")
f.close()